# PHYNFRA - Python Houer Infrastructure
# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "phynfra"
authors = ["Jaime Daniel Corrêa Mendes <jaimedaniel@houer.com.br>"]
description = "Phynfra - Python Houer Infraestructure"
readme = "readme.md"
license = "Owner"
version = "3.0.0"

[tool.poetry.scripts]
phynfra = "phynfra.__main__:main"

[tool.poetry.dependencies]
python = ">=3.9"
boto3 = "*"
deltalake = "*"
delta-spark = "*"
openpyxl = "*"
pandas = "*"
python-dotenv = "*"
pyspark = ">=3.5,<4.0"
requests = "*"
pytz = "*"	
pyjwt = "*"
cryptography = "*"
slack_sdk = "*"
watchtower = ">=3.4.0,<4.0.0"
uuid7 = ">=0.1.0,<0.2.0"
pyyaml = ">=6.0,<7.0"

[poetry.group.dev.dependencies]
poetry = "*"

[[tool.poetry.include]]
path = "phynfra/boilerplate/*"

[[tool.poetry.include]]
path = "license.txt"
