[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{{name}}"
version = "{{version}}"
requires-python = ">=3.9"
dependencies = [{{dependencies}}]

[tool.setuptools]
package-dir = {"" = "."}
py-modules = [{{modules}}]

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]
